cart/urls.py
from os import name
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    path('add/<uuid:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<uuid:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<uuid:product_id>/', views.full_remove, name='full_remove'),
    path('full_remove1/', views.full_remove1, name='full_remove1'),
]

order/urls.py
from django.urls import path
from order import views
from . import views
from .views import orderHistory, orderDetail

app_name = 'order'

urlpatterns = [
    path('thanks/<int:order_id>/', views.thanks, name='thanks'),
    path('history/', orderHistory.as_view(), name='order_history'),
    path('<int:order_id>/', orderDetail.as_view(), name='order_detail'),  
]

pcshop_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.urls.conf import re_path
from django.views.generic.base import TemplateView
from django.conf.urls.static import static

from django.views.static import serve

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('shop.urls')),
    path('search/', include('search_app.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('vouchers/', include('vouchers.urls')),
    #re_path(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    #re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

search_app/urls.py
from django.urls import path
from .views import SearchResultsListView

app_name = 'search_app'

urlpatterns = [
    path('', SearchResultsListView.as_view(), name='searchResult'),
]

shop/urls.py
from os import name
from django.urls import path
from .views import ProdCat, ProdDetail

from . import views

app_name = 'shop'

urlpatterns = [
    path('', ProdCat.as_view(), name='allProdCat'),
    path('about/', views.about, name='about'),
    path('<uuid:category_id>/', ProdCat.as_view(), name='products_by_category'),
    path('<uuid:category_id>/<uuid:product_id>/', ProdDetail.as_view(), name = 'prod_detail'),
]

shop/models.py
import uuid
from django.db import models
from django.urls import reverse

class Category(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='category', blank=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'
    
    def get_absolute_url(self):
        return reverse('shop:products_by_category', args=[self.id])
    
    def __str__(self):
        return self.name


class Product(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False)
    
    name = models.CharField(max_length=250, unique=True)
    description = models.TextField(blank=True)
    description_two = models.TextField(blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='product', blank=True)
    stock = models.IntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True, blank=True, null=True)
    updated = models.DateTimeField(auto_now=True, blank=True, null=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'product'
        verbose_name_plural = 'products'
    
    def get_absolute_url(self):
        return reverse('shop:prod_detail', args=[self.category.id, self.id])
    
    def __str__(self):
        return self.name

shop/views.py
from django.core import paginator
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.views.generic import ListView, DetailView
from django.core.paginator import Page, Paginator, EmptyPage, InvalidPage
from django.views.generic import TemplateView

class ProdDetail(DetailView):
    model = Product

    def get(self, request, category_id, product_id):
        try:
            product = Product.objects.get(category_id = category_id, id = product_id)
        except Exception as e:
            raise e
        return render(request, "shop/product.html",{'product':product})



class ProdCat(ListView):
    model = Product

    def get(self,request, category_id=None):
        category = None
        products = None
        if category_id != None:
            category = get_object_or_404(Category, id = category_id)
            products = Product.objects.filter(category = category, available = True)
        else:
            products = Product.objects.all().filter(available = True)
        
        paginator = Paginator(products, 6)
        try:
            page = int(request.GET.get('page', '1'))
        except:
            page = 1
        try:
            products = paginator.page(page)
        except (EmptyPage, InvalidPage):
            products = paginator.page(paginator.num_pages)
        
        return render(request, "shop/category.html",{'category':category, 'products':products})

def about(request):
    return render(request, 'about.html')

shop/templates/about.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css"
	integrity="sha256-2XFplPlrFClt0bIdPgpz8H7ojnk10H69xRqd9+uTShA=" crossorigin="anonymous" />
<section class="deneb_cta">
	<div class="container">
		<div class="cta_wrapper">
			<div class="row align-items-center">
				<div class="col-lg-7">
					<div class="cta_content">
						<h3>About us</h3>
						<p>We are one of Europe's biggest online PC shops for pc parts and hardware. All our parts come
							with the highest degree of quality and we have one of the most competitive price around!</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<footer class="deneb_footer">
	<div class="widget_wrapper"
		style="background-image: url(http://demo.tortoizthemes.com/deneb-html/deneb-ltr/assets/images/footer_bg.png);">
		<div class="container">
			<div class="row">
				<div class="col-lg-4 col-md-6 col-12">
					<div class="widget widegt_about">
						<div class="widget_title">
							<img src="assets/images/logo_1.png" class="img-fluid" alt="">
						</div>
						<p>Want to know more about us? Feel free to follow our social networks to find out about special
							offers, discounts, events... And much more!</p>
						<ul class="social">
							<li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
							<li><a href="#"><i class="fab fa-twitter"></i></a></li>
							<li><a href="#"><i class="fab fa-instagram"></i></a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-4 col-md-6 col-sm-12">
					<div class="widget widget_link">
						<div class="widget_title">
							<h4>Links</h4>
						</div>
						<ul>
							<li><a href="#">About Us</a></li>
							<li><a href="#">Services</a></li>
							<li><a href="#">Portfolio</a></li>
							<li><a href="#">Blog</a></li>
						</ul>
					</div>
				</div>
				<div class="col-lg-4 col-md-6 col-sm-12">
					<div class="widget widget_contact">
						<div class="widget_title">
							<h4>Contact Us</h4>
						</div>
						<div class="contact_info">
							<div class="single_info">
								<div class="icon">
									<i class="fas fa-phone-alt"></i>
								</div>
								<div class="info">
									<p><a href="#">( 01) 437 0969</a></p>
									<p><a href="#">	+353 1 437 0969</a></p>
								</div>
							</div>
							<div class="single_info">
								<div class="icon">
									<i class="fas fa-envelope"></i>
								</div>
								<div class="info">
									<p><a href="#">info@pccomponentsLTD.com</a></p>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</footer>
{% endblock content %}

shop/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" crossorigin="anonymous">
    <meta name="description" content="{% block metadescription %}{% endblock %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/navbar.css' %}">
</head>

<body>
    <div class="container">
        {% include 'navbar-fixed.html' %}
        {% block content %}
        {% endblock %}
        {% include 'footer.html' %}
    </div>

    <!-- Separate Popper and Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-
IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>
</body>
</html>

shop/templates/footer.html
<div class="footer navbar-fixed-bottom my-footer">
    <p class="text-center">&copy; PC Components Ltd. All Rights Reserved.</p>
</div>

shop/templates/header.html
{% load static %}
<header>
    <div style="text-align: center;">
        <a href="{% url 'shop:allProdCat' %}"><img src="{% static 'images/logo2.png' %}" width="100" height="100" alt="PC-Store"></a>
    </div>
</header>

shop/templates/navbar-fixed.html
<link rel="stylesheet" href="/static/css/custom.css">
<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'shop:allProdCat' %}"><img src="/static/images/logo2.png" width="75" height="75" alt=""></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        Shop
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'shop:allProdCat' %}">All Products</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        {% for cat in links %}
                        <li><a class="dropdown-item" href="{{cat.get_absolute_url}}">{{cat.name}}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cart:cart_detail' %}">Your Cart</a>
                </li>
            </ul>
            <form class="d-flex" action="{% url 'search_app:searchResult' %}" method="get">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
                <button class="btn btn-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
            </form>
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class=" nav-link dropdown-toggle" href="#" id="navbarDropdown" data-bs-toggle="dropdown"
                    aria-expanded="false">
                    {{ user.username }}
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                    <li><a class="dropdown-item" href="{% url 'order:order_history' %}">Order history</a></li>
                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'signout' %}">Sign Out</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'signin' %}">Log In</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'shop:about' %}">About</a>
            </li>
        </div>
    </div>
</nav>

shop/templates/navbar.html
<nav class="navbar fixed-top navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#"><img src="/static/images/logo2.png" width="75" height="75" alt=""></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bstarget="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" ariaexpanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                        shop
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'shop:allProdCat' %}">All Products</a></li>
                        {% for cat in links %}
                        <li><a class="dropdown-item" href="{{cat.get_absolute_url}}">{{cat.name}}</a></li>
                        {% endfor %}
                    </ul>
                </li>
                {% if item_count > 0 %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'cart:cart_detail' %}"><i class="fas fa-shopping-cart"></i> Your
                        Cart</a>
                </li>
                {% endif %}
                {% if user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class=" nav-link dropdown-toggle" href="#" id="navbarDropdown" data-bs-toggle="dropdown"
                        aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'order:order_history' %}">Order history</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'signout' %}">Sign Out</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'signin' %}">Sign In</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'shop:about' %}">About</a>
                </li>
            </ul>
            <form class="d-flex" action="{% url 'search_app:searchResult' %}" method="get">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q">
                <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>